# Generated by Django 4.2.13 on 2024-07-04 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior a 0 estrelas.'), django.core.validators.MaxValueValidator(10, 'Avaliação não pode ser superior a 10 estrelas.')]),
        ),
    ]
